name: CheckLinks

# **What it does**: Runs a weekly check for broken internal links.
# **Why we have it**: We want to make sure that pages we link to work.
# **Who does it impact**: Everyone



on:
  schedule:
    - cron: "5 4 * * SAT"

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Yarn install
        run: yarn install
      - name: Build jekyll website with
        run: bundle exec jekyll build
      - name: Check for broken links
        run: |
          yarn run hyperlink ./_site/index.html --canonicalroot https://segment.com/docs -i -r --skip 0.0.0.0 | yarn run tap-spot > output.md
        continue-on-error: true
      - name: Archive log links
        uses: actions/upload-artifact@v1
        with:
          name: links-check.log
          path: output.md
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: output.md
          labels: report, automated issue
